### PR TITLE
MD5 deprecated, Sha256 hash check

### PR DESCRIPTION
**Pull request by xewl**
Since the HMAC-check isn't being done via md5 anymore, here's some new logic. 
I've followed the rules from the documentation. $query_params would be equal to the full $_GET-object.

### CODE REVIEW

**Comment by EiNSTeiN-** [comment]
@sandeepshetty would it be possible to merge this? The complete deprecation of the legacy md5 `signature` will happen soon.

**Comment by hsleewis** [comment]
@sandeepshetty can you please merge this, deprecation of the legacy md5 signature will happen the day after tomorrow.

**Comment by gnikyt** [comment]
+1 I just temporarily fixed this for a couple legacy apps we had in our system that weren't Ruby based. I patched it directly in the Composer vendor folder but if this was merged and pushed to Composer, I could update it properly and that would be great!

Just a note however, Shopify seems to include `protocol` into the query string now (ex protcol=https://), `http_build_query` seems encode the `https://` part which caused an issue for me, not sure if it did for anyone else. I had to use `urldecode` around the `http_build_query` to make the HMAC string valid and match.

**Comment by xewl** [comment]
The http_build_query will be removed from this snippet, because it's encoding too much. (overdoing it)
Decoding the builded query would result in other random flaws.

It seems that the documentation only wants us to decode 3 specific characters, and leave the rest alone.
A patch to my fork is coming from another coder, and I will pull it in when the pull request is in.

**Comment by xewl** [comment]
Please note: Corrected handling of the hmac has now been added by @marekgach

**Comment by EiNSTeiN-** [comment]
FYI the `signature` parameter has been completely removed as of last month so you no longer need the line

```
unset($query_params['signature']);
```

**Comment by xewl** [comment]
And it seems, that suddenly people, ~~wake up~~ contribute! (:

**Comment by LukeTowers** [comment]
@xewl @EiNSTeiN- @hsleewis @ohmybrew feel free to give my version a try: https://github.com/LukeTowers/php-shopify-api

**Comment by xewl** [comment]
@LukeTowers I've been using my patch for soooo long now.. x)

**Comment by LukeTowers** [comment]
@xewl You know what they say, don't fix what ain't broke 😉

**Comment by xewl** [comment]
@LukeTowers That's what they say -- 99% not what needs to be done :(

**Comment by xewl** [comment]
Closed due to lost repository.
Check @LukeTowers 's repo for a fix.

**Pull request closed without merging**
